# Databases {#databases}

Our database is designed with user security and anonymity in mind. The database is split into four tables:

```
- Users         - Encrypted, holds personal information
- Accounts      - Plain text, holds all accounts and their balance
- Transactions  - Plain text, holds all transactions
- Logging       - Plain text, used to log pseudo-anonymous activity
```

This structure was made with one thing in mind; To give the user control of their information. This is achieved by encrypting the users table, which prevents
updating or reading the information without the users password. This forces developers to always keep security in mind, since he/she cant alter or read usable information from database without having the users permission. The drawback on the other hand is that we need another way to temporarily store the users decrypted information while they are logged in.


## Users {#databases-users}

Users is a database of registered users, their 2fa `secret` key, and their accounts. This table does not contain any unencrypted or hashed information.

**User table Fields**
```python
class User(db.Model, UserMixin):
    email = db.Column(db.String(80), primary_key=True, unique=True, nullable=False)
    enEmail = db.Column(db.String(80), nullable=False)
    password = db.Column(db.String(200), nullable=False)
    enKey = db.Column(db.String(128))
    accounts = db.Column(db.String(10000))
    secret = db.Column(db.String(32 + 128))

    # If the user is not found in redis,
    # the user is effectively not logged in
    @property
    def is_authenticated(self):
        # Check if the current_user is logged in
        if redis.get(self.email):
            # If so set data to expire 10 minutes from now
            redis.expire(self.email, 3600)
            # return true to the flask login manager
            return True
        return False

    #essentially same as above property
    @property
    def is_active(self):
        if redis.get(self.email):
            redis.expire(self.email, 3600)
            return True
        return False
```

- `email` is the users identifier. It is stored in in a hashed state, without salt. The reason for hashing this is simply to have a fixed length for database lookup entries.

- `enEmail` is the users clear text email encrypted with the users Fernet key.

- `password` is the users hashed password concatenated with the salt used to hash it. The `salt` is the only thing stored in plain text. The resulting hash and salt is always the same length and thereby we can split this information into its respective parts.

- `enKey` is the users encryption-key that has been encrypted by the users hashed password without salt. This creates a new unique hash that is different from the salted password hash above. This hash is not done for security reasons, its purpose is to create a fixed length 32 byte key to encrypt the encryption key.

- `accounts` holds account ownership information that is encrypted with the encryption key.

- `secret` is the secret key used to generate One Time Passcodes (OTP's). 

As shown all the data in this database table is either encrypted or hashed. While we certainly will always do everything we can to secure both physical and remote access, the worst case scenario should always be considered. The way this is structured, the user could potentially leave the website open on their computer and still be confident that no one could make changes to their account.

## Accounts {#databases-accounts}

Accounts is a table containing all banking accounts and their balance. Accounts are "use and dispose" meaning they are be easy to create and not limited in supply.

```python
class Account(db.Model):
    number = db.Column(db.String(11), unique=True, nullable=False, primary_key=True)
    balanceField = db.Column(db.String(256))  
    # tallet viser til maks lengde av et siffer

    # Henter verdien fra databasen og konverterer til streng
    @property
    def balance(self):
        return int(self.balanceField)

    # setter verdien i databasen, dersom den er en int, blir den til streng
    @balance.setter
    def balance(self, value):
        # Sjekker om jeg faar en int, ellers skal det ikke fungere.
        if type(value) == int:
            value = str(value)
            self.balanceField = value
        else:
            raise Exception("Can only set this to be an int")

```

- `account` is the account number. We use the standard `xxxx yy zzzzc` format. 
    - `xxxx`    is a bank registration number which identify the bank.
    - `yy`      signifies account type, where we have only one. 
    - `zzzz`    is the customers account number.
    - `c`       is the "control-digit". Calculated by **xxxxyyzzzz**%10

- `balance` is a property of the account, it converts the balance into an int since its stored as a string. This is to prevent rounding errors. 

Nothing in the accounts table is encrypted.


## Transactions {#databases-transactions}

Transactions is a database containing all transactions.

```python
class Transactions(db.Model):
    transactionID = db.Column(db.Integer, primary_key=True)
    accountFrom = db.Column(db.String(80), nullable=False)
    accountTo = db.Column(db.String(80), nullable=False, )
    amountDB = db.Column(db.String(256))
    message = db.Column(db.String(90))
    time = db.Column(DateTime, default=datetime.datetime.utcnow,nullable=False)
```

- `transactionID` is a unique transaction id associated with the transaction.

- `accountFrom` transaction origin.
 
- `accountTo` transaction destination.

- `amountDB` amount being sent. 

- `message` a short message/number sent along with the transaction. This could plain text or a KID-message.

- `time` a time-stamp for the transaction.

The data in transactions table is not encrypted, but since the users table which holds ownership information is encrypted there is no direct way to find which user made the transaction. A user could potentially compromise their own or the receivers anonymity by writing personal information in the message field.
