# Database

Some notation:
- `(a)` means the hash of `a` is stored.
- `((a))` means an encrypted form of `a` is stored.

## Users

```
(email)  (pw+salt)  salt  ((2fa_secret))  ((n_accs))  ((accs+priv_keys))
```

- `email` is the users identifier. It is stored in a cryptographically hashed state to allow for the plaintext email to be used as part of an encryption key.

- `pw` is the users password. It is stored as a cryptographical hash of itself prepended to a salt. This prevents rainbow table attacks on the database.

- `salt` is the only thing stored in plaintext and is a cryptographically random number.

- `2fa_secret` is the secret key used to generate One Time Passcodes (OTP's). It is encrypted using the users email and password.

- `n_accs` is simply the number of accounts the user has. It is encrypted using the users email and password.

- `accs+priv_keys` is simply a long list containing all account numbers associated with the user and the private key associated with that account. It is encrypted using the users email and password.

## Accounts

```
(acc)  public_key  balance
```

- `acc` is the account number. It is stored as a cryptograhpical hash. This allows us to prevent a class of attacks where an account of interesting balance can be traced backwards. It is of course still possible to get a hold of this database and check forwards to see what balance an account holds.

- `public_key` is the public key associated with the account. It is used to verify transactions from the account.

- `balance` is simply the balance of the account.

## Transactions

```
uid  date  timeout  (from)  (to)  amount  sign
```

- `uid` is a unique transaction id associated with the account. This is included to make sure a signed transaction can only be counted once.

- `date` is the timestamp of when the transaction was made. Probably UNIX time.

- `timeout` is a timestamp of when the transaction should expire. This prevents transactions that fail being reused by a bad actor some time in the future.

- `from` is the account number that is transferring. It is stored as a cryptographic hash to prevent the backtracking discussed earlier.

- `to` is the account number that is receiving. It is stored as a cryptographic hash to prevent the backtracking discussed earlier.

- `amount` is the amount that is transferring. Note that this can not be more than the balance of the `from` account.

- `sign` is the signature of the transaction, signed with the `private_key` of the `from` account. If the transaction is changed in any way then this signature must also change, preventing transactions being reused.
