# Registration
On the registration page, the user will have to input the following

## Email
At Safecoin, the users email will be used as the username. During the registration process, the email will be hashed with scrypts hash-function without a salt, and compared with the other hashed emails in the database. The page will return a generic error if it is already in use. 

## Password
The users password is cryptographically hashed with scrypt and a random salt. The salt is generated together with the password, and prevent any malicious party from being able to compare hashes to figure out what anyones password is. For simple and non-intrusive password rules, the users password must be 12 characters or longer in length, as well as not be only numbers, e.g. "123456789101112". The simplicity and swiftness of cracking passwords that are short is far more dangerous than other generic password rules such as needing to contain a number and special character. We also compare the users password to a pre-defined list containing common passwords to ensure some form of complexity.

Due to the fact that scrypt is being used for the password hashing, the password can, within reason, be as long as the user wants "NEEDS SOURCE". When the user inputs a valid password, the password gets hashed together with a randomly generated salt. The hashed password is stored alongside its salt in a dictionary until the registration process is complete. 

## TwoFactor Authentication
If the user passes both the email and password-checks, the user will be sent over to a page where two-factor-authentication will be activated. The user will be presented a QR-code that can be scanned in ones authenticator app of choice, e.g. google authenticator, authy or microsoft authenticator. In the app the user user will have a code that will continually be renewed after a certain amount of time. The user needs to submit their password once again and type in their generated TOTP-code. By making the user use their TOTP code, we simultaneously ensure they have added the secret-key to their app of choice, as they couldn't generate the TOTP without having done so.

Having completed this check, the user is added to the database and is allowed to log in.
